# example netlify.toml
[build]
  command = "# no build command"
  publish = "public"

#[[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200

[[redirects]]
  from = "/api/data"
  to = "https://transformer.huggingface.co/autocomplete/gpt2/xl"
  status = 200
  force = true